version: '3.4'

services:
  congether:
    image: schnell/congether
    restart: always
    environment: 
      Congether__Db__ConnectionString: mongodb://congether-mongodb:27017/congether
      Congether__Db__DefaultDatabase: congether
      Congether__Listener: http://*:5000
    depends_on: 
      - mongodb
    networks:
      - app-network
    ports: 
      - "5000"

  mongodb:
    container_name: congether-mongodb
    restart: always
    image: mongo
    networks:
      - app-network

  nginx:
    container_name: congether-nginx
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - congether
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
